media: assets
content:
  - name: Home
    label: Homepage
    path: index.html
    type: file
    fields:
    - name: hero
      label: Hero
      type: object
      fields: 
      - { name: title, label: Title, type: string }
      - { name: body, label: Body copy, type: string}
      - { name: buttonText, label: Button text, type: string}
      - { name: url, label: URL, type: string }
      - { name: image, label: Image, type: image}